name: Bots

on:
  # PR synchronization is a push into a branch associated with the PR
  pull_request:
    types: [opened, edited, synchronize, labeled, unlabeled]
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  call_bedevere:
    name: Call Bedevere
    runs-on: ubuntu-latest
    steps:
      - uses: arhadthedev/bedevere@6282d6c676db2e8a6ce68cb2de77b780be22ee1e
        with:
          token: ${{ secrets.BEDEVERE_PAT }}
          event: ${{ toJSON(github.event) }}
